# Generated by Django 3.2.15 on 2022-11-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_api', '0002_parkinglot_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='area',
        ),
    ]
