branch-defaults:
  develop:
    environment: sp-api
    group_suffix: null
  main:
    environment: null
    group_suffix: null
global:
  application_name: smart-parking
  branch: null
  default_ec2_keyname: maple
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
