# Generated by Django 4.1.3 on 2022-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_alter_profilefeeditem_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_plate',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
