# Generated by Django 4.1.3 on 2022-11-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_remove_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_numeber',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
