# Generated by Django 4.1.3 on 2022-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_userprofile_phone_numeber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
