# Generated by Django 4.1.3 on 2022-11-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_api", "0006_userprofile_is_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="phone_numeber", new_name="phone_number",
        ),
    ]
