# Generated by Django 4.1.3 on 2022-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_duration',
            field=models.FloatField(default=10),
        ),
    ]
