# Generated by Django 4.1.3 on 2022-11-06 11:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(default=((0, 0), (0, 0), (0, 0), (0, 0), (0, 0)), srid=27700),
        ),
    ]
