# Generated by Django 4.1.3 on 2022-11-06 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0002_parkinglot_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longtitude', models.FloatField(default=0)),
                ('lattitude', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='area',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='area',
            field=models.ManyToManyField(to='parking_lot.corner'),
        ),
    ]
